function DuckRotL (tAngle: number) {
    pins.digitalWritePin(DigitalPin.P16, 1)
    servos.P2.setAngle(tAngle)
    basic.pause(200)
    pins.digitalWritePin(DigitalPin.P16, 0)
    basic.pause(500)
}
function DuckRotR (tAngle: number) {
    pins.digitalWritePin(DigitalPin.P8, 1)
    servos.P2.setAngle(tAngle)
    basic.pause(200)
    pins.digitalWritePin(DigitalPin.P8, 0)
    basic.pause(500)
}
input.onButtonPressed(Button.A, function () {
    basic.showString("F")
    DuckRotR(90)
    DuckRotR(75)
    DuckRotR(60)
    DuckRotR(45)
    DuckRotR(30)
    DuckRotL(45)
    DuckRotL(60)
    DuckRotL(75)
    DuckRotL(90)
    DuckRotL(105)
    DuckRotL(120)
    DuckRotL(135)
    DuckRotL(150)
    DuckRotR(135)
    DuckRotR(120)
    DuckRotR(105)
    DuckRotR(90)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(2000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showString("R")
    DuckRotL(90)
    DuckRotL(105)
    DuckRotL(120)
    DuckRotL(135)
    DuckRotL(150)
    DuckRotR(135)
    DuckRotR(120)
    DuckRotR(105)
    DuckRotR(90)
    DuckRotR(75)
    DuckRotR(60)
    DuckRotR(45)
    DuckRotR(30)
    DuckRotL(45)
    DuckRotL(60)
    DuckRotL(75)
    DuckRotL(90)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(2000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.clearScreen()
})
basic.showIcon(IconNames.Heart)
pins.digitalWritePin(DigitalPin.P0, 0)
pins.digitalWritePin(DigitalPin.P1, 0)
servos.P2.setPulse(15000)
servos.P2.setRange(30, 150)
servos.P2.setAngle(90)
basic.pause(1000)
basic.clearScreen()
